### ISSUE TITLE
F41+ has python 3.13 by default, we require 3.12

### ISSUE THREAD

**Issue by nikromen** [fedora-copr/resalloc-ibm-cloud#29]
see build fails for F41+:

```
Problem: conflicting requests
  - nothing provides python(abi) = 3.12 needed by python3-ibm-vpc-0.20.0-1.fc40.noarch from fedora
  - nothing provides (python3.12dist(python-dateutil) < 3~~ with python3.12dist(python-dateutil) >= 2.5.3) needed by python3-ibm-vpc-0.20.0-1.fc40.noarch from fedora
  - nothing provides python3.12dist(ibm-cloud-sdk-core) >= 3.16.7 needed by python3-ibm-vpc-0.20.0-1.fc40.noarch from fedora

Copr build error: Build failed
```

**Comment by xsuchy** [comment]
I know, it requires urllib2 which should land in a few days in rawhide.

**Comment by praiskup** [comment]
https://stackoverflow.com/a/63233379/11045205 do you mean urllib3?

**Comment by praiskup** [comment]
Ah, urllib3 v2, that's funny.

**Comment by praiskup** [comment]
> in a few days in rawhide.

What is the plan for F41?

**Comment by xsuchy** [comment]
https://src.fedoraproject.org/rpms/python-urllib3/pull-request/22

**Comment by xsuchy** [comment]
> What is the plan for F41?

Big unknown. Most likely revert and bump up epoch. :(

**Comment by xsuchy** [comment]
This is resolved now. F41 has bumped epoch and rolled back one version.
And rawhide has recent release.
https://koji.fedoraproject.org/koji/packageinfo?packageID=34894
